environment          = "#{environment}"
lambda_function_name = "#{lambda_function_name}"
lambda_s3_bucket     = "#{lambda_s3_bucket}"
lambda_s3_key        = "#{lambda_s3_key}"
schedule_expression  = "#{schedule_expression}"
